[[plugins]]
repo = 'hoob3rt/lualine.nvim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'glepnir/lspsaga.nvim'

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'drewtempelmeyer/palenight.vim'

[[plugins]]
repo = 'rakr/vim-one'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'xiyaowong/nvim-transparent'

[[plugins]]
repo = 'nvim-lua/completion-nvim'

[[plugins]]
repo = 'nvim-lua/popup.nvim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'

[[plugins]]
repo = 'norcalli/nvim-colorizer.lua'
