apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
spec:
  containers:
  - name: nvidia-gpu
    image: nvidia/cuda:11.0-base
    resources:
      limits:
        nvidia.com/gpu: 1  # Request 1 GPU
    command: ["nvidia-smi"]
  restartPolicy: Never

