[language-server.basedpyright]
command = "basedpyright-langserver"
args = ["--stdio"]

[language-server.gpt]
command = "helix-gpt"

[[language]]
name = "python"
scope ="source.python"
auto-format = true
injection-regex = "python"
indent = { tab-width = 4, unit = "    " }
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = [ { name = "basedpyright" }, { name = "ruff-lsp" }, {name = "gpt"}]
shebangs = [ "python" ]

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.ruff-lsp.config]
settings = {args = ["format", "-"]}

[language-server.ruff]
command = "ruff-lsp"
config = { settings = { run = "onSave" } }

[language.formatter]
command = "ruff"
args = ["format", "-"]

[language-server.rust-analyzer.config]
check.command = "clippy"

[[language]]
name = "ocaml"
auto-format = true

[language.formatter]
command = "ocamlformat"
args = [ "-" ]
