[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.ruff-lsp]
command = "ruff-lsp"

[language-server.ruff-lsp.config]
settings = {args = ["format", "-"]}

[[language]]
name = "python"
scope ="source.python"
auto-format = true
injection-regex = "python"
indent = { tab-width = 4, unit = "    " }
roots = ["pyproject.toml", "pyrightconfig.json", "Poetry.lock"]
language-servers = [ { name = "pyright" }, { name = "ruff-lsp" } ]
shebangs = [ "python" ]
